'use client';
import * as React from 'react';
import Head from 'next/head';
import { Container, Typography, AppBar, Toolbar, Box, Button, IconButton } from '@mui/material';
import { ThemeProvider } from '@mui/material/styles';
import { ArrowForward, ArrowBack } from '@mui/icons-material';
import theme from './theme.js';

function Location() {
  const [locations] = React.useState([
    [
      { name: 'Beverly Hills', address: '123 Beverly Hills Blvd, Beverly Hills, CA' },
      { name: 'Santa Monica', address: '456 Santa Monica Blvd, Santa Monica, CA' },
      { name: 'Hollywood', address: '789 Hollywood Blvd, Hollywood, CA' },
    ],
    [
      { name: 'Venice', address: '101 Venice Beach, Venice, CA' },
      { name: 'Westwood', address: '202 Westwood Blvd, Los Angeles, CA' },
      { name: 'Brentwood', address: '303 Brentwood Ave, Los Angeles, CA' },
    ],
    [
      { name: 'Pasadena', address: '404 Pasadena Ave, Pasadena, CA' },
      { name: 'Downtown LA', address: '505 Downtown LA, Los Angeles, CA' },
      { name: 'Culver City', address: '606 Culver City Blvd, Culver City, CA' },
    ],
  ]);

  const [currentLocationSet, setCurrentLocationSet] = React.useState(0);

  const handleNavigate = (direction) => {
    if (direction === 'next' && currentLocationSet < locations.length - 1) {
      setCurrentLocationSet(currentLocationSet + 1);
    } else if (direction === 'prev' && currentLocationSet > 0) {
      setCurrentLocationSet(currentLocationSet - 1);
    }
  };

  const handleDirectNavigation = (index) => {
    setCurrentLocationSet(index);
  };

  const handleLocationClick = (location) => {
    alert(`You selected: ${location.name} - ${location.address}`);
  };

  return (
    <React.StrictMode>
      <ThemeProvider theme={theme}>
        <Head>
          <title>Pantry Raid Co - Pantry Tracker</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="favicon.ico" />
        </Head>

        {/* Background */}
        <Box
          sx={{
            display: 'flex',
            backgroundColor: '#ffebcc', // Pale orange color
            height: '100vh',
            width: '100vw',
            position: 'fixed',
            zIndex: -1,
          }}
        />

        {/* AppBar */}
        <AppBar position="fixed" color="secondary">
          <Toolbar>
            <img src="cart.png" alt="PantryRaid Co. Logo" key="logo" style={{ marginRight: 10, height: 30 }} />
            <Typography variant="h6" component="div" color="white" fontFamily="Bubblegum Sans" fontSize="3" sx={{ flexGrow: 1 }}>
              PantryRaid Co.
            </Typography>
          </Toolbar>
        </AppBar>

        {/* Main Content */}
        <main>
          <Container
            maxWidth="md"
            sx={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              height: '100vh',
              position: 'relative',
            }}
          >
            {/* Main Box */}
            <Box
              sx={{
                backgroundColor: '#ffae42', // Darker orange shade
                padding: '30px', // Inner padding for spacing
                borderRadius: '12px', // Rounded corners
                boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)', // Subtle shadow
                textAlign: 'center', // Center-align text inside
                width: '100%',
                maxWidth: '700px', // Fixed box width
                position: 'absolute',
                top: '50%',
                left: '50%',
                transform: 'translate(-50%, -50%)', // Center the box
              }}
            >
              <Typography variant="h2" color="primary" component="h1" mb={2} fontFamily="Pacifico" sx={{ textDecoration: 'underline' }}>
                Locations near [Zip Code]
              </Typography>

              {/* Show the current set of locations */}
              {locations[currentLocationSet].map((location, index) => (
                <Button
                  key={index}
                  onClick={() => handleLocationClick(location)}
                  sx={{
                    display: 'block',
                    width: '100%',
                    textAlign: 'left',
                    padding: '15px',
                    backgroundColor: '#ff8c1a',
                    borderRadius: '8px',
                    mb: 2,
                    color: 'white',
                    textTransform: 'none',
                    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)', // Subtle shadow
                    '&:hover': {
                      backgroundColor: '#e87a15',
                    },
                  }}
                >
                  <Typography variant="h5" color="white" fontWeight="bold">
                    {location.name}
                  </Typography>
                  <Typography variant="body1" color="white" sx={{ fontSize: '1rem' }}>
                    {location.address}
                  </Typography>
                </Button>
              ))}

              {/* Pagination Controls */}
              <Box
                sx={{
                  display: 'flex',
                  justifyContent: 'center',
                  alignItems: 'center',
                  mt: 2,
                }}
              >
                <IconButton onClick={() => handleNavigate('prev')} color="primary" sx={{ mx: 1 }}>
                  <ArrowBack />
                </IconButton>
                {[0, 1, 2].map((option) => (
                  <Button
                    key={option}
                    onClick={() => handleDirectNavigation(option)}
                    sx={{
                      mx: 1,
                      fontWeight: currentLocationSet === option ? 'bold' : 'normal',
                      backgroundColor: currentLocationSet === option ? '#e87a15' : '#ff8c1a',
                      color: 'white',
                      '&:hover': {
                        backgroundColor: '#e87a15',
                      },
                    }}
                  >
                    {option + 1}
                  </Button>
                ))}
                <IconButton onClick={() => handleNavigate('next')} color="primary" sx={{ mx: 1 }}>
                  <ArrowForward />
                </IconButton>
              </Box>
            </Box>
          </Container>
        </main>
      </ThemeProvider>
    </React.StrictMode>
  );
}

export default Location;
