'use client';
import * as React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { Container, Typography, AppBar, Toolbar, Box, Button } from '@mui/material';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme.js';

function Search() {
  const [selectedOptions, setSelectedOptions] = React.useState([]);

  const questions = [
    {
      question: 'What are you looking for?',
      options: [
        'Price',
        'Comfort',
        'Safety',
        'Space',
        'Efficiency',
        'Reliability',
      ],
    },
    // The second question and any others are removed
  ];

  const handleOptionClick = (option) => {
    if (selectedOptions.length < 3 || selectedOptions.includes(option)) {
      let newSelectedOptions = [...selectedOptions];

      if (newSelectedOptions.includes(option)) {
        // Deselect the option if it's already selected
        newSelectedOptions = newSelectedOptions.filter(item => item !== option);
      } else {
        // Select the option if there is room
        newSelectedOptions.push(option);
      }

      setSelectedOptions(newSelectedOptions);
    }
  };

  const { question, options } = questions[0]; // Always use the first question

  return (
    <React.StrictMode>
      <ThemeProvider theme={theme}>
        <Head>
          <title>Pantry Raid Co - Pantry Tracker</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="favicon.ico" />
        </Head>

        {/* Background */}
        <Box
          sx={{
            display: 'flex',
            backgroundColor: '#ffebcc', // Pale orange color
            height: '100vh',
            width: '100vw',
            position: 'fixed',
            zIndex: -1,
          }}
        />

        {/* AppBar */}
        <AppBar position="fixed" color="secondary">
          <Toolbar>
            <img src="cart.png" alt="PantryRaid Co. Logo" key="logo" style={{ marginRight: 10, height: 30 }} />
            <Typography variant="h6" component="div" color="white" fontFamily="Bubblegum Sans" fontSize="3" sx={{ flexGrow: 1 }}>
              PantryRaid Co.
            </Typography>
          </Toolbar>
        </AppBar>

        {/* Main Content */}
        <main>
          <Container maxWidth="md" sx={{ paddingTop: '80px' }}>
            <Box
              sx={{
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                flexDirection: 'column',
                height: 'calc(100vh - 64px)', // Full height minus AppBar height
              }}
            >
              {/* Decorative Box Around the Question */}
              <Box
                sx={{
                  backgroundColor: '#ffae42', // Darker orange shade
                  padding: '30px', // Inner padding for spacing
                  borderRadius: '12px', // Rounded corners
                  boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)', // Subtle shadow
                  textAlign: 'center', // Center-align text inside
                  width: '100%',
                  maxWidth: '700px', // Fixed box width
                  height: '600px', // Fixed box height
                  mb: 2, // Margin below the box
                  mt: 2,
                }}
              >
                <Typography variant="h2" color="primary" component="h1" mb={2} fontFamily="Pacifico" sx={{ textDecoration: 'underline' }}>
                  {question}
                </Typography>
                <Typography variant="h4" color="white" fontSize="1.5rem" mt={2} mb={4}>
                  Please select <strong>three options</strong> out of the six provided below.
                </Typography>
                {/* Options within the same decorative box */}
                <Box
                  sx={{
                    display: 'flex',
                    flexDirection: 'column',
                    gap: 2, // Space between buttons
                  }}
                >
                  {options.map((option, index) => {
                    return (
                      <Button
                        key={index}
                        variant="contained"
                        color={selectedOptions.includes(option) ? 'primary' : 'secondary'}
                        sx={{
                          textTransform: 'none', // Keep text case
                          fontSize: '1rem', // Larger font size
                          padding: '10px 20px', // Spacing
                          color: '#ffffff', // Corrected color property (hex format)
                          backgroundColor: selectedOptions.includes(option) ? '#d9534f' : '#d59a00', // Red when selected, dark yellow when not
                          opacity: selectedOptions.length >= 3 && !selectedOptions.includes(option) ? 0.5 : 1, // Disable unselected options when 3 selections are made
                        }}
                        onClick={() => handleOptionClick(option)}
                        disabled={selectedOptions.length >= 3 && !selectedOptions.includes(option)} // Disable unselected options after 3 selections
                      >
                        <strong>{option}</strong>
                      </Button>
                    );
                  })}
                </Box>
              </Box>

              {/* Submit Button */}
              <Box display="flex" justifyContent="center" alignItems="center" mt={0.5}>
                <Link href="/swipe"> {/* Link to the next page */}
                  <Button
                    variant="contained"
                    color="primary"
                    sx={{
                      padding: '1px 20px',
                      fontSize: '1.5rem',
                      color: '#ffffff',
                      fontFamily: 'Bubblegum Sans',
                    }}
                    disabled={selectedOptions.length !== 3} // Disable submit button if 3 options aren't selected
                  >
                    Submit
                  </Button>
                </Link>
              </Box>
            </Box>
          </Container>
        </main>
      </ThemeProvider>
    </React.StrictMode>
  );
}

export default Search;
